# fly.toml app configuration file generated for gw2-randomizer-bot on 2025-11-20T22:51:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gw2-randomizer-bot'
primary_region = 'bom'

[build]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
